name: java-action
description: simple hello world java action
author: I-DevR

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  milliseconds:
    description: write hello world
    required: true
    default: 'world'

# Define your outputs here.
outputs:
  result:
    description: The result of the action
  completion_status:
    description: Indicates whether the action completed successfully
  time:
    description: description goes here

runs:
  using: node20
  main: dist/index.js
